"""Planted-hierarchy purity macros for the camera-ready (answers Q3).

Reads the sealed 500-graph scale audit and writes paired purity differences
between the NEST row (SE-NNI-fast) and each external baseline.  Every value in
the paper's purity sentence comes from this file; nothing is typed by hand.
"""
import json
import pathlib

import numpy as np
import scipy.stats as st

ROOT = pathlib.Path(__file__).resolve().parents[1]
AUDIT = ROOT / "results" / "scale-audit-20260810"
OUT = ROOT / "paper" / "se-hier-nni" / "tables" / "purity_macros.tex"
REGIMES = ["clean", "noisy", "imbalanced", "weighted", "weak"]
NEST = "SE-NNI-fast"
BASELINES = {"HCSE": "HCSE", "BBM": "BBM"}


def load():
    by_method = {}
    for regime in REGIMES:
        records = json.loads((AUDIT / f"n64-{regime}.json").read_text())["records"]
        for rec in records:
            if rec.get("status") == "ok":
                by_method.setdefault(rec["method"], {})[(regime, rec["seed"])] = rec
    return by_method


def purity(rec, method, kind):
    # The NEST row is the refined endpoint; baselines are scored as returned.
    prefix = "final" if method == NEST else "raw"
    return rec[f"{prefix}_{kind}_purity"]


def main():
    data = load()
    keys = sorted(data[NEST])
    assert len(keys) == 500, len(keys)
    lines = []
    for kind, tag in [("fine", "Fine"), ("coarse", "Coarse")]:
        nest = np.array([purity(data[NEST][k], NEST, kind) for k in keys])
        lines.append(rf"\newcommand{{\Purity{tag}NEST}}{{{nest.mean():.3f}}}")
        for name, method in BASELINES.items():
            assert set(data[method]) == set(keys)
            base = np.array([purity(data[method][k], method, kind) for k in keys])
            diff = nest - base
            half = st.t.ppf(0.975, len(diff) - 1) * diff.std(ddof=1) / np.sqrt(len(diff))
            lines += [
                rf"\newcommand{{\Purity{tag}{name}}}{{{base.mean():.3f}}}",
                rf"\newcommand{{\Purity{tag}Gain{name}}}{{{diff.mean():.3f}}}",
                rf"\newcommand{{\Purity{tag}Gain{name}CI}}{{{half:.3f}}}",
                rf"\newcommand{{\Purity{tag}Lower{name}}}{{{int((diff < 0).sum())}/{len(diff)}}}",
            ]
    OUT.write_text("% Generated by scripts/make_purity_macros.py; do not edit.\n"
                   + "\n".join(lines) + "\n")
    print(f"WROTE {OUT.relative_to(ROOT)}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
