"""Macros for the camera-ready answers to Reviewer 3 (items 1-4).

Every number comes from a results file:
* results/nest_certificate_audit.json   (scripts/audit_nest_certificate.py)
* results/nest_compound_sensitivity.json (scripts/sensitivity_compound.py)
* results/scale-audit-20260810/n64-*.json (sealed operator audit)
* results/nni_restart_fairness.json and exact14/16 (sealed exact audit)
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "results"
OUT = ROOT / "paper" / "se-hier-nni" / "tables" / "review3_macros.tex"
STEMS = ["clean", "noisy", "imbalanced", "weighted", "weak"]


def main():
    cert = json.loads((RES / "nest_certificate_audit.json").read_text())["summary"]
    assert cert["graphs"] == 500 and cert["matches_sealed"] == 500
    sens = json.loads((RES / "nest_compound_sensitivity.json").read_text())["summary"]

    ops = []
    for stem in STEMS:
        ops += [r for r in json.loads((RES / "scale-audit-20260810" / f"n64-{stem}.json")
                                      .read_text())["records"] if r.get("status") == "ok"]
    bbm = [r for r in ops if r["method"] == "BBM"]
    barriers = [r["max_barrier"] for r in ops
                if r["method"] != "SE-NNI-fast" and r["compound_moves"] > 0]

    exact = []
    for path in [RES / "nni_restart_fairness.json",
                 RES / "scale-audit-20260810" / "exact14.json",
                 RES / "scale-audit-20260810" / "exact16.json"]:
        exact += json.loads(path.read_text())["records"]
    hcse_unique = [r["outcomes"]["HCSE-B32"]["unique_entropies_1e-10"] for r in exact]
    bbm_unique = [r["outcomes"]["BBM-label-free-B32"]["unique_entropies_1e-10"] for r in exact]

    sel = cert["selected_initializer"]
    b64, b4 = sens["b=64"], sens["b=4"]
    unchanged = all(sens[k]["max_abs_change"] < 1e-3
                    for k in ["beta=0.01", "beta=0.2", "R=2", "R=32"])
    assert unchanged
    lines = [
        rf"\newcommand{{\CertGraphs}}{{{cert['certified']}/{cert['graphs']}}}",
        rf"\newcommand{{\CertBinary}}{{{cert['binary']}/{cert['graphs']}}}",
        rf"\newcommand{{\CertFromAgg}}{{{sel.get('SE-agglomerative', 0)}}}",
        rf"\newcommand{{\CertFromParis}}{{{sel.get('external-0', 0)}}}",
        rf"\newcommand{{\CertMaxDescent}}{{{cert['max_descent_moves_selected']}}}",
        rf"\newcommand{{\CertMaxCompound}}{{{cert['max_compound_moves_selected']}}}",
        rf"\newcommand{{\BBMBudgetHits}}{{{sum(r['nni1_moves'] >= 100 for r in bbm)}/{len(bbm)}}}",
        rf"\newcommand{{\MaxBarrier}}{{{max(barriers):.3f}}}",
        rf"\newcommand{{\HCSEMaxDistinct}}{{{max(hcse_unique)}}}",
        rf"\newcommand{{\BBMDistinctRange}}{{{min(bbm_unique)}--{max(bbm_unique)}}}",
        rf"\newcommand{{\SensBSixtyFourGain}}{{{-b64['mean_change_vs_default']:.4f}}}",
        rf"\newcommand{{\SensBSixtyFourLower}}{{{b64['graphs_lower']}/50}}",
        rf"\newcommand{{\SensBFourLoss}}{{{b4['mean_change_vs_default']:.4f}}}",
        rf"\newcommand{{\SensBFourHigher}}{{{b4['graphs_higher']}/50}}",
    ]
    OUT.write_text("% Generated by scripts/make_review3_macros.py; do not edit.\n"
                   + "\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
